<PSOC_DB>
  <PSOC_PROJECT_LIST>
    <PSOC_PROJECT PATH="\lab1\lab1.cmx" IS_ACTIVE="FALSE" />
    <PSOC_PROJECT PATH="\lab2\lab2.cmx" IS_ACTIVE="FALSE" />
    <PSOC_PROJECT PATH="\Lab3B\Lab3B.cmx" IS_ACTIVE="FALSE" />
    <PSOC_PROJECT PATH="\Lab3D\Lab3D.cmx" IS_ACTIVE="TRUE" />
  </PSOC_PROJECT_LIST>
</PSOC_DB>