//*****************************************************************************
//*****************************************************************************
//  FILENAME:  SCGain.h  ( SCBLOCK )
//  Version: 2.4, Updated on 2015/3/4 at 22:26:58
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION:  SCBLOCK User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef SCGain_INCLUDE
#define SCGain_INCLUDE

#include <M8C.h>

//-------------------------------------------------
// Constants for SCGain API's.
//-------------------------------------------------
#define SCGain_OFF         0
#define SCGain_LOWPOWER    1
#define SCGain_MEDPOWER    2
#define SCGain_HIGHPOWER   3

#pragma fastcall16 SCGain_Start
#pragma fastcall16 SCGain_SetPower
#pragma fastcall16 SCGain_Stop

//-------------------------------------------------
// Prototypes of the SCGain API.
//-------------------------------------------------
extern void SCGain_Start(BYTE bPower);
extern void SCGain_SetPower(BYTE bPower);
extern void SCGain_Stop(void);

//-------------------------------------------------
// Register Addresses for SCGain
//-------------------------------------------------
#pragma ioport  SCGain_cr0: 0x090
BYTE            SCGain_cr0;
#pragma ioport  SCGain_cr1: 0x091
BYTE            SCGain_cr1;
#pragma ioport  SCGain_cr2: 0x092
BYTE            SCGain_cr2;
#pragma ioport  SCGain_cr3: 0x093
BYTE            SCGain_cr3;
#pragma ioport  SCGain_Comp_Ctrl:   0x000
BYTE            SCGain_Comp_Ctrl;

#endif
// end of file SCGain.h
