/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// Button_input address and mask defines
#pragma	ioport	Button_input_Data_ADDR:	0x4
BYTE			Button_input_Data_ADDR;
#pragma	ioport	Button_input_DriveMode_0_ADDR:	0x104
BYTE			Button_input_DriveMode_0_ADDR;
#pragma	ioport	Button_input_DriveMode_1_ADDR:	0x105
BYTE			Button_input_DriveMode_1_ADDR;
#pragma	ioport	Button_input_DriveMode_2_ADDR:	0x7
BYTE			Button_input_DriveMode_2_ADDR;
#pragma	ioport	Button_input_GlobalSelect_ADDR:	0x6
BYTE			Button_input_GlobalSelect_ADDR;
#pragma	ioport	Button_input_IntCtrl_0_ADDR:	0x106
BYTE			Button_input_IntCtrl_0_ADDR;
#pragma	ioport	Button_input_IntCtrl_1_ADDR:	0x107
BYTE			Button_input_IntCtrl_1_ADDR;
#pragma	ioport	Button_input_IntEn_ADDR:	0x5
BYTE			Button_input_IntEn_ADDR;
#define Button_input_MASK 0x1
