/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// PWMOut2 address and mask defines
#pragma	ioport	PWMOut2_Data_ADDR:	0x0
BYTE			PWMOut2_Data_ADDR;
#pragma	ioport	PWMOut2_DriveMode_0_ADDR:	0x100
BYTE			PWMOut2_DriveMode_0_ADDR;
#pragma	ioport	PWMOut2_DriveMode_1_ADDR:	0x101
BYTE			PWMOut2_DriveMode_1_ADDR;
#pragma	ioport	PWMOut2_DriveMode_2_ADDR:	0x3
BYTE			PWMOut2_DriveMode_2_ADDR;
#pragma	ioport	PWMOut2_GlobalSelect_ADDR:	0x2
BYTE			PWMOut2_GlobalSelect_ADDR;
#pragma	ioport	PWMOut2_IntCtrl_0_ADDR:	0x102
BYTE			PWMOut2_IntCtrl_0_ADDR;
#pragma	ioport	PWMOut2_IntCtrl_1_ADDR:	0x103
BYTE			PWMOut2_IntCtrl_1_ADDR;
#pragma	ioport	PWMOut2_IntEn_ADDR:	0x1
BYTE			PWMOut2_IntEn_ADDR;
#define PWMOut2_MASK 0x1
// PWMOut3 address and mask defines
#pragma	ioport	PWMOut3_Data_ADDR:	0x0
BYTE			PWMOut3_Data_ADDR;
#pragma	ioport	PWMOut3_DriveMode_0_ADDR:	0x100
BYTE			PWMOut3_DriveMode_0_ADDR;
#pragma	ioport	PWMOut3_DriveMode_1_ADDR:	0x101
BYTE			PWMOut3_DriveMode_1_ADDR;
#pragma	ioport	PWMOut3_DriveMode_2_ADDR:	0x3
BYTE			PWMOut3_DriveMode_2_ADDR;
#pragma	ioport	PWMOut3_GlobalSelect_ADDR:	0x2
BYTE			PWMOut3_GlobalSelect_ADDR;
#pragma	ioport	PWMOut3_IntCtrl_0_ADDR:	0x102
BYTE			PWMOut3_IntCtrl_0_ADDR;
#pragma	ioport	PWMOut3_IntCtrl_1_ADDR:	0x103
BYTE			PWMOut3_IntCtrl_1_ADDR;
#pragma	ioport	PWMOut3_IntEn_ADDR:	0x1
BYTE			PWMOut3_IntEn_ADDR;
#define PWMOut3_MASK 0x10
// SwitchIn address and mask defines
#pragma	ioport	SwitchIn_Data_ADDR:	0x4
BYTE			SwitchIn_Data_ADDR;
#pragma	ioport	SwitchIn_DriveMode_0_ADDR:	0x104
BYTE			SwitchIn_DriveMode_0_ADDR;
#pragma	ioport	SwitchIn_DriveMode_1_ADDR:	0x105
BYTE			SwitchIn_DriveMode_1_ADDR;
#pragma	ioport	SwitchIn_DriveMode_2_ADDR:	0x7
BYTE			SwitchIn_DriveMode_2_ADDR;
#pragma	ioport	SwitchIn_GlobalSelect_ADDR:	0x6
BYTE			SwitchIn_GlobalSelect_ADDR;
#pragma	ioport	SwitchIn_IntCtrl_0_ADDR:	0x106
BYTE			SwitchIn_IntCtrl_0_ADDR;
#pragma	ioport	SwitchIn_IntCtrl_1_ADDR:	0x107
BYTE			SwitchIn_IntCtrl_1_ADDR;
#pragma	ioport	SwitchIn_IntEn_ADDR:	0x5
BYTE			SwitchIn_IntEn_ADDR;
#define SwitchIn_MASK 0x8
// PWMOut1 address and mask defines
#pragma	ioport	PWMOut1_Data_ADDR:	0x4
BYTE			PWMOut1_Data_ADDR;
#pragma	ioport	PWMOut1_DriveMode_0_ADDR:	0x104
BYTE			PWMOut1_DriveMode_0_ADDR;
#pragma	ioport	PWMOut1_DriveMode_1_ADDR:	0x105
BYTE			PWMOut1_DriveMode_1_ADDR;
#pragma	ioport	PWMOut1_DriveMode_2_ADDR:	0x7
BYTE			PWMOut1_DriveMode_2_ADDR;
#pragma	ioport	PWMOut1_GlobalSelect_ADDR:	0x6
BYTE			PWMOut1_GlobalSelect_ADDR;
#pragma	ioport	PWMOut1_IntCtrl_0_ADDR:	0x106
BYTE			PWMOut1_IntCtrl_0_ADDR;
#pragma	ioport	PWMOut1_IntCtrl_1_ADDR:	0x107
BYTE			PWMOut1_IntCtrl_1_ADDR;
#pragma	ioport	PWMOut1_IntEn_ADDR:	0x5
BYTE			PWMOut1_IntEn_ADDR;
#define PWMOut1_MASK 0x10
