<PSOC_DB>
  <PSOC_PROJECT_LIST>
    <PSOC_PROJECT PATH="\Lab4B\Lab4B.cmx" IS_ACTIVE="FALSE" />
    <PSOC_PROJECT PATH="\Lab4C\Lab4C.cmx" IS_ACTIVE="FALSE" />
    <PSOC_PROJECT PATH="\Lab4D\Lab4D.cmx" IS_ACTIVE="TRUE" />
    <PSOC_PROJECT PATH="\Lab4A\Lab4A.cmx" IS_ACTIVE="FALSE" />
  </PSOC_PROJECT_LIST>
</PSOC_DB>