//*****************************************************************************
//*****************************************************************************
//  FILENAME: MuteTimer.h
//   Version: 2.60, Updated on 2015/3/4 at 22:23:47
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Counter8 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef MuteTimer_INCLUDE
#define MuteTimer_INCLUDE

#include <m8c.h>

#pragma fastcall16 MuteTimer_EnableInt
#pragma fastcall16 MuteTimer_DisableInt
#pragma fastcall16 MuteTimer_Start
#pragma fastcall16 MuteTimer_Stop
#pragma fastcall16 MuteTimer_bReadCounter              // Read  DR0
#pragma fastcall16 MuteTimer_WritePeriod               // Write DR1
#pragma fastcall16 MuteTimer_bReadCompareValue         // Read  DR2
#pragma fastcall16 MuteTimer_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 bMuteTimer_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 bMuteTimer_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the MuteTimer API.
//-------------------------------------------------

extern void MuteTimer_EnableInt(void);                           // Proxy Class 1
extern void MuteTimer_DisableInt(void);                          // Proxy Class 1
extern void MuteTimer_Start(void);                               // Proxy Class 1
extern void MuteTimer_Stop(void);                                // Proxy Class 1
extern BYTE MuteTimer_bReadCounter(void);                        // Proxy Class 1
extern void MuteTimer_WritePeriod(BYTE bPeriod);                 // Proxy Class 1
extern BYTE MuteTimer_bReadCompareValue(void);                   // Proxy Class 2
extern void MuteTimer_WriteCompareValue(BYTE bCompareValue);     // Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern BYTE bMuteTimer_ReadCounter(void);            // Deprecated
extern BYTE bMuteTimer_ReadCompareValue(void);       // Deprecated


//--------------------------------------------------
// Constants for MuteTimer API's.
//--------------------------------------------------

#define MuteTimer_CONTROL_REG_START_BIT        ( 0x01 )
#define MuteTimer_INT_REG_ADDR                 ( 0x0e1 )
#define MuteTimer_INT_MASK                     ( 0x40 )


//--------------------------------------------------
// Constants for MuteTimer user defined values
//--------------------------------------------------

#define MuteTimer_PERIOD                       ( 0xa0 )
#define MuteTimer_COMPARE_VALUE                ( 0x64 )


//-------------------------------------------------
// Register Addresses for MuteTimer
//-------------------------------------------------

#pragma ioport  MuteTimer_COUNTER_REG:  0x038              //DR0 Count register
BYTE            MuteTimer_COUNTER_REG;
#pragma ioport  MuteTimer_PERIOD_REG:   0x039              //DR1 Period register
BYTE            MuteTimer_PERIOD_REG;
#pragma ioport  MuteTimer_COMPARE_REG:  0x03a              //DR2 Compare register
BYTE            MuteTimer_COMPARE_REG;
#pragma ioport  MuteTimer_CONTROL_REG:  0x03b              //Control register
BYTE            MuteTimer_CONTROL_REG;
#pragma ioport  MuteTimer_FUNC_REG: 0x138                  //Function register
BYTE            MuteTimer_FUNC_REG;
#pragma ioport  MuteTimer_INPUT_REG:    0x139              //Input register
BYTE            MuteTimer_INPUT_REG;
#pragma ioport  MuteTimer_OUTPUT_REG:   0x13a              //Output register
BYTE            MuteTimer_OUTPUT_REG;
#pragma ioport  MuteTimer_INT_REG:       0x0e1             //Interrupt Mask Register
BYTE            MuteTimer_INT_REG;


//-------------------------------------------------
// MuteTimer Macro 'Functions'
//-------------------------------------------------

#define MuteTimer_Start_M \
   MuteTimer_CONTROL_REG |=  MuteTimer_CONTROL_REG_START_BIT

#define MuteTimer_Stop_M  \
   MuteTimer_CONTROL_REG &= ~MuteTimer_CONTROL_REG_START_BIT

#define MuteTimer_EnableInt_M   \
   M8C_EnableIntMask(MuteTimer_INT_REG, MuteTimer_INT_MASK)

#define MuteTimer_DisableInt_M  \
   M8C_DisableIntMask(MuteTimer_INT_REG, MuteTimer_INT_MASK)

#endif
// end of file MuteTimer.h
