<PSOC_DB>
  <PSOC_PROJECT_LIST>
    <PSOC_PROJECT PATH="\Lab3B\Lab3B.cmx" IS_ACTIVE="FALSE" />
    <PSOC_PROJECT PATH="\Lab3D\Lab3D.cmx" IS_ACTIVE="TRUE" />
    <PSOC_PROJECT PATH="\Lab3A\Lab3A.cmx" IS_ACTIVE="FALSE" />
    <PSOC_PROJECT PATH="\Lab3C\Lab3C.cmx" IS_ACTIVE="FALSE" />
  </PSOC_PROJECT_LIST>
</PSOC_DB>